# Generated by Django 6.0.3 on 2026-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='nitrogen',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='ph_level',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='phosphorus',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='user',
        ),
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_photos/'),
        ),
        migrations.AddField(
            model_name='farm',
            name='intended_crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
