# Generated by Django 6.0.3 on 2026-03-24 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_farm_name_remove_farm_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(default='My Farm', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='nitrogen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='ph_level',
            field=models.FloatField(default=7.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='phosphorus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(default='Loamy', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_pics/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intended_crop',
            field=models.CharField(default='Rice', max_length=100),
        ),
    ]
