# Generated by Django 6.0.3 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_created_at_farm_farm_name_farm_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intended_crop',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
