# Generated by Django 5.2.8 on 2026-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_farm_image_farm_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
