# Generated by Django 5.2.8 on 2026-03-26 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_farm_location_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockchainLog',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='name',
            new_name='farm_name',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='intended_crop',
            field=models.CharField(default='Rice', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location_name',
            field=models.CharField(default='Unknown Village', max_length=255),
        ),
        migrations.AlterField(
            model_name='farm',
            name='nitrogen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phosphorus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(default='Loamy', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
